sudo: required

language: c

compiler:
    - clang
    - gcc

before_script:
    - sudo add-apt-repository ppa:dns/gnu -y
    - sudo apt-get update -q
    - sudo apt-get install -qy valgrind
    - sudo apt-get install --only-upgrade autoconf automake
    - autoreconf -vi

script:
    - ./configure
    - make
    - make check
    - echo "q" | valgrind --error-exitcode=1 --leak-check=yes ./PZ80emu test.bin
    - make clean
    - ./configure --enable-code-coverage
    - make check-code-coverage
