sudo: required

language: c

compiler:
    - clang
    - gcc

before_script:
    - sudo add-apt-repository ppa:dns/gnu -y
    - sudo apt-get update -q
    - sudo apt-get install -qy valgrind
    - sudo apt-get install --only-upgrade autoconf automake
    - autoreconf -vi

script:
    - ./configure --enable-code-coverage
    - make check-code-coverage
